pipeline:
  name: a1
  identifier: a1
  projectIdentifier: whai
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1708418859437
        repoName: fig-gabriel/newlife
        build: <+input>
  stages:
    - stage:
        name: a1
        identifier: a1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: a1
                  identifier: a1
                  template:
                    templateRef: account.yay
                    versionLabel: ver1
