pipeline:
  name: a5
  identifier: a5
  projectIdentifier: tesst
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1708418859437
        repoName: fig-gabriel/newlife
        build: <+input>
  stages:
    - stage:
        name: a5
        identifier: a5
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: a5
                  identifier: a5
                  template:
                    templateRef: account.yay
                    versionLabel: ver1
