pipeline:
  name: b2
  identifier: b2
  projectIdentifier: tesst
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1708418859437
        repoName: fig-gabriel/newlife
        build: <+input>
  stages:
    - stage:
        name: b2
        identifier: b2
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: b2
                  identifier: b2
                  template:
                    templateRef: account.arm64
                    versionLabel: arm64
