pipeline:
  name: betlogtite
  identifier: betlogtite
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: uhuh
        build: <+input>
  stages:
    - stage:
        name: kmjhngfbvd
        identifier: kmjhngfbvd
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: a
                  identifier: a
                  template:
                    templateRef: account.yep
                    versionLabel: "1"
