pipeline:
  name: biboos
  identifier: biboos
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: keith
        build: <+input>
  stages:
    - stage:
        name: babee
        identifier: babee
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: babs
                  identifier: babs
                  template:
                    templateRef: account.yes
                    versionLabel: "yes"
