pipeline:
  name: feelmahd
  identifier: feelmahd
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: keith
        build: <+input>
  stages:
    - stage:
        name: dd
        identifier: dd
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: cam
                  identifier: cam
                  template:
                    templateRef: account.yes
                    versionLabel: "yes"
