pipeline:
  name: monkawscary
  identifier: monkawscary
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: uhuh
        build: <+input>
  stages:
    - stage:
        name: scary
        identifier: scary
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: hahee
                  identifier: hahee
                  template:
                    templateRef: yay
                    versionLabel: yay1
