pipeline:
  name: trollerface
  identifier: trollerface
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: uhuh
        build: <+input>
  stages:
    - stage:
        name: trollinface
        identifier: trollinface
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: ass
                  identifier: ass
                  template:
                    templateRef: yay
                    versionLabel: yay1
