pipeline:
  name: v
  identifier: v
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1708716129236
        repoName: fig-gabriel/newlife
        build: <+input>
  stages:
    - stage:
        name: v
        identifier: v
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: v
                  identifier: v
                  template:
                    templateRef: account.a
                    versionLabel: a
