pipeline:
  name: Build newlife
  identifier: Build_fig_gabriel_newlife_1709657158790
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  name: news
                  identifier: news
                  template:
                    templateRef: account.yes
                    versionLabel: "yes"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1709657148325
        repoName: fig-gabriel/newlife
        build: <+input>
