pipeline:
  name: Build newlife
  identifier: Build_fig_gabriel_newlife_1708716143026
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  template:
                    templateRef: account.a
                    versionLabel: a
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1708716129236
        repoName: fig-gabriel/newlife
        build: <+input>
